2024-11-21 14:14:44,752 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-11-21 14:15:09,926 WARNING django.request Not Found: /
2024-11-21 14:15:09,928 WARNING django.server "GET / HTTP/1.1" 404 2928
2024-11-21 14:15:52,054 WARNING django.request Not Found: /
2024-11-21 14:15:52,054 WARNING django.server "GET / HTTP/1.1" 404 2928
2024-11-21 14:15:57,657 INFO django.server "GET /admin/ HTTP/1.1" 302 0
2024-11-21 14:15:57,721 INFO django.server "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
2024-11-21 14:15:57,816 INFO django.server "GET /static/admin/css/login.css HTTP/1.1" 200 958
2024-11-21 14:15:57,826 INFO django.server "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
2024-11-21 14:15:57,827 INFO django.server "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
2024-11-21 14:15:57,829 INFO django.server "GET /static/admin/css/base.css HTTP/1.1" 200 21544
2024-11-21 14:15:57,829 INFO django.server "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
2024-11-21 14:15:57,829 INFO django.server "GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
2024-11-21 14:15:57,829 INFO django.server "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
2024-11-21 14:15:57,891 WARNING django.request Not Found: /favicon.ico
2024-11-21 14:15:57,892 WARNING django.server "GET /favicon.ico HTTP/1.1" 404 2979
2024-11-21 14:16:02,540 INFO django.server "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4319
2024-11-21 14:16:02,662 WARNING django.request Not Found: /favicon.ico
2024-11-21 14:16:02,662 WARNING django.server "GET /favicon.ico HTTP/1.1" 404 2979
2024-11-21 14:21:44,636 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-11-21 14:22:13,054 WARNING django.request Not Found: /
2024-11-21 14:22:13,054 WARNING django.server "GET / HTTP/1.1" 404 2928
2024-11-21 14:22:13,159 WARNING django.request Not Found: /favicon.ico
2024-11-21 14:22:13,160 WARNING django.server "GET /favicon.ico HTTP/1.1" 404 2979
2024-11-21 14:22:16,134 INFO django.server "GET /admin/ HTTP/1.1" 302 0
2024-11-21 14:22:16,162 INFO django.server "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
2024-11-21 14:31:46,092 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-11-21 14:31:52,543 WARNING django.request Not Found: /
2024-11-21 14:31:52,544 WARNING django.server "GET / HTTP/1.1" 404 2928
2024-11-21 14:31:57,648 INFO django.server "GET /admin/ HTTP/1.1" 302 0
2024-11-21 14:31:57,714 INFO django.server "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
2024-11-21 14:31:57,813 INFO django.server "GET /static/admin/css/base.css HTTP/1.1" 304 0
2024-11-21 14:31:57,819 INFO django.server "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
2024-11-21 14:31:57,820 INFO django.server "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
2024-11-21 14:31:57,821 INFO django.server "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
2024-11-21 14:31:57,823 INFO django.server "GET /static/admin/js/theme.js HTTP/1.1" 304 0
2024-11-21 14:31:57,824 INFO django.server "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
2024-11-21 14:31:57,825 INFO django.server "GET /static/admin/css/login.css HTTP/1.1" 304 0
2024-11-21 14:32:09,988 INFO django.server "OPTIONS /register/ HTTP/1.1" 200 0
2024-11-21 14:32:10,293 INFO django.server "POST /register/ HTTP/1.1" 201 157
2024-11-21 14:32:10,403 INFO django.server "OPTIONS /api/users/3/ HTTP/1.1" 200 0
2024-11-21 14:32:10,405 INFO django.server "OPTIONS /api/files/ HTTP/1.1" 200 0
2024-11-21 14:32:10,406 INFO django.server "OPTIONS /api/users/ HTTP/1.1" 200 0
2024-11-21 14:32:10,439 INFO django.server "GET /api/users/3/ HTTP/1.1" 200 48
2024-11-21 14:32:10,439 INFO django.server "GET /api/files/ HTTP/1.1" 200 2
2024-11-21 14:32:10,440 INFO django.server "GET /api/users/ HTTP/1.1" 200 50
2024-11-21 14:41:23,314 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-11-21 14:41:39,584 INFO django.server "OPTIONS /register/ HTTP/1.1" 200 0
2024-11-21 14:41:39,883 INFO django.server "POST /register/ HTTP/1.1" 201 158
2024-11-21 14:41:40,001 INFO django.server "OPTIONS /api/users/36/ HTTP/1.1" 200 0
2024-11-21 14:41:40,003 INFO django.server "OPTIONS /api/files/ HTTP/1.1" 200 0
2024-11-21 14:41:40,003 INFO django.server "OPTIONS /api/users/ HTTP/1.1" 200 0
2024-11-21 14:41:40,023 INFO django.server "GET /api/users/36/ HTTP/1.1" 200 49
2024-11-21 14:41:40,029 INFO django.server "GET /api/users/ HTTP/1.1" 200 51
2024-11-21 14:41:40,029 INFO django.server "GET /api/files/ HTTP/1.1" 200 2
2024-11-21 14:43:15,261 INFO django.server "GET /api/users/36/ HTTP/1.1" 200 49
2024-11-21 14:43:15,292 INFO django.server "GET /api/users/36/ HTTP/1.1" 200 49
2024-11-21 14:43:15,444 INFO django.server "GET /api/users/36/ HTTP/1.1" 200 49
2024-11-21 14:43:15,447 INFO django.server "GET /api/files/ HTTP/1.1" 200 2
2024-11-21 14:43:15,449 INFO django.server "GET /api/users/ HTTP/1.1" 200 51
2024-11-21 14:43:28,193 INFO django.server "OPTIONS /logout/ HTTP/1.1" 200 0
2024-11-21 14:43:28,209 INFO django.server "GET /logout/ HTTP/1.1" 200 89
2024-11-21 14:43:47,491 INFO django.server "OPTIONS /login/ HTTP/1.1" 200 0
2024-11-21 14:43:47,769 INFO django.server "POST /login/ HTTP/1.1" 200 139
2024-11-21 14:43:47,872 INFO django.server "OPTIONS /api/users/2/ HTTP/1.1" 200 0
2024-11-21 14:43:47,889 INFO django.server "GET /api/files/ HTTP/1.1" 200 283
2024-11-21 14:43:47,894 INFO django.server "GET /api/users/ HTTP/1.1" 200 501
2024-11-21 14:43:47,896 INFO django.server "GET /api/users/2/ HTTP/1.1" 200 113
2024-11-21 14:43:52,100 INFO django.server "GET /api/users/2/ HTTP/1.1" 200 113
2024-11-21 14:43:52,117 INFO django.server "GET /api/users/2/ HTTP/1.1" 200 113
2024-11-21 14:43:52,200 INFO django.server "GET /api/files/ HTTP/1.1" 200 283
2024-11-21 14:43:52,204 INFO django.server "GET /api/users/ HTTP/1.1" 200 501
2024-11-21 15:07:59,655 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-11-21 17:40:29,421 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-11-21 17:41:29,275 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-11-21 17:41:34,407 INFO django.server "OPTIONS /login/ HTTP/1.1" 200 0
2024-11-21 17:41:34,705 INFO django.server "POST /login/ HTTP/1.1" 200 139
2024-11-21 17:41:34,850 INFO django.server "OPTIONS /api/users/2/ HTTP/1.1" 200 0
2024-11-21 17:41:34,851 INFO django.server "OPTIONS /api/users/ HTTP/1.1" 200 0
2024-11-21 17:41:34,854 INFO django.server "OPTIONS /api/files/ HTTP/1.1" 200 0
2024-11-21 17:41:34,887 INFO django.server "GET /api/users/2/ HTTP/1.1" 200 113
2024-11-21 17:41:34,889 INFO django.server "GET /api/files/ HTTP/1.1" 200 283
2024-11-21 17:41:34,890 INFO django.server "GET /api/users/ HTTP/1.1" 200 501
2024-11-21 17:41:40,193 INFO django.server "OPTIONS /api/users/2/ HTTP/1.1" 200 0
2024-11-21 17:41:40,193 INFO django.server "OPTIONS /api/users/ HTTP/1.1" 200 0
2024-11-21 17:41:40,193 INFO django.server "OPTIONS /api/files/ HTTP/1.1" 200 0
2024-11-21 17:41:40,225 INFO django.server "GET /api/users/2/ HTTP/1.1" 200 113
2024-11-21 17:41:40,225 INFO django.server "GET /api/files/ HTTP/1.1" 200 283
2024-11-21 17:41:40,228 INFO django.server "GET /api/users/ HTTP/1.1" 200 501
2024-11-21 17:46:09,093 INFO django.utils.autoreload Watching for file changes with StatReloader
2024-11-21 17:46:14,274 INFO django.server "OPTIONS /login/ HTTP/1.1" 200 0
2024-11-21 17:46:14,558 INFO django.server "POST /login/ HTTP/1.1" 200 139
2024-11-21 17:46:14,707 INFO django.server "OPTIONS /api/users/2/ HTTP/1.1" 200 0
2024-11-21 17:46:14,708 INFO django.server "OPTIONS /api/users/ HTTP/1.1" 200 0
2024-11-21 17:46:14,709 INFO django.server "OPTIONS /api/files/ HTTP/1.1" 200 0
2024-11-21 17:46:14,766 INFO django.server "GET /api/users/2/ HTTP/1.1" 200 113
2024-11-21 17:46:14,776 INFO django.server "GET /api/files/ HTTP/1.1" 200 283
2024-11-21 17:46:14,777 INFO django.server "GET /api/users/ HTTP/1.1" 200 501
2024-11-21 17:46:45,774 INFO django.server "OPTIONS /login/ HTTP/1.1" 200 0
2024-11-21 17:46:46,141 ERROR django.request Internal Server Error: /login/
Traceback (most recent call last):
  File "/app/accounts/views.py", line 48, in login_view
    token = Token.objects.get(user=authenticated_user)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 647, in get
    raise self.model.DoesNotExist(
rest_framework.authtoken.models.Token.DoesNotExist: Token matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "user_id" of relation "authtoken_token" violates not-null constraint
DETAIL:  Failing row contains (38764ce93d7e45c04abd0f85288ece326540b651, 2024-11-21 17:46:46.056245+00, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/app/accounts/views.py", line 50, in login_view
    token = Token.objects.create(user=authenticated_user)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 677, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/authtoken/models.py", line 33, in save
    return super().save(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 901, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1059, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1100, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1845, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "user_id" of relation "authtoken_token" violates not-null constraint
DETAIL:  Failing row contains (38764ce93d7e45c04abd0f85288ece326540b651, 2024-11-21 17:46:46.056245+00, null).

2024-11-21 17:46:46,144 ERROR django.server "POST /login/ HTTP/1.1" 500 189290
2024-11-21 17:46:48,816 INFO django.server "OPTIONS /register/ HTTP/1.1" 200 0
2024-11-21 17:46:49,117 INFO django.server "POST /register/ HTTP/1.1" 201 138
2024-11-21 17:46:49,292 INFO django.server "OPTIONS /api/files/ HTTP/1.1" 200 0
2024-11-21 17:46:49,292 INFO django.server "OPTIONS /api/users/37/ HTTP/1.1" 200 0
2024-11-21 17:46:49,293 INFO django.server "OPTIONS /api/users/ HTTP/1.1" 200 0
2024-11-21 17:46:49,321 INFO django.server "GET /api/files/ HTTP/1.1" 200 2
2024-11-21 17:46:49,323 INFO django.server "GET /api/users/37/ HTTP/1.1" 200 39
2024-11-21 17:46:49,329 INFO django.server "GET /api/users/ HTTP/1.1" 200 41
2024-11-21 17:47:13,223 INFO django.server "OPTIONS /api/files/ HTTP/1.1" 200 0
2024-11-21 17:47:13,223 INFO django.server "OPTIONS /api/users/ HTTP/1.1" 200 0
2024-11-21 17:47:13,223 INFO django.server "OPTIONS /api/users/37/ HTTP/1.1" 200 0
2024-11-21 17:47:13,283 INFO django.server "GET /api/files/ HTTP/1.1" 200 2
2024-11-21 17:47:13,286 INFO django.server "GET /api/users/ HTTP/1.1" 200 41
2024-11-21 17:47:13,289 INFO django.server "GET /api/users/37/ HTTP/1.1" 200 39
2024-11-21 17:47:16,490 INFO django.server "OPTIONS /logout/ HTTP/1.1" 200 0
2024-11-21 17:47:16,517 INFO django.server "GET /logout/ HTTP/1.1" 200 69
2024-11-21 17:47:20,214 INFO django.server "OPTIONS /login/ HTTP/1.1" 200 0
2024-11-21 17:47:20,219 WARNING django.request Bad Request: /login/
2024-11-21 17:47:20,219 WARNING django.server "POST /login/ HTTP/1.1" 400 89
